### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-tarasenko#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
7) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу клонування Private GitHub-репозиторіїв. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by GromZz** [comment]
Ось кілька основних причин, чому GitHub ввів використання токенів доступу для клонування приватних репозиторіїв: забезпечення безпеки, управління правами доступу, зручність, більша безпека для користувачів, підтримка для двофакторної аутентифікації. Узагальнюючи, використання токенів доступу для клонування приватних репозиторіїв на GitHub допомагає підвищити безпеку, зручність та контроль над доступом до репозиторіїв для користувачів та організацій.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
